name: Formatter_ex Build and Test
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Build project
        run: |
          mkdir build && cd build
          cmake ..
          make
      - name: Run tests
        run: make test
